### PR TITLE
Corner radius animation

### PR DESCRIPTION
**Pull request by nunogoncalves**
Added corner radius animation feature. 

from: https://github.com/IFTTT/JazzHands/issues/1495

@jhersh here it is. If I need to do anything else let me know.

### CODE REVIEW

**Comment by jhersh** [comment]
Thanks @nunogoncalves!

**Comment by revolter** [comment]
Any idea why isn't this working for me? I use this to register the keyframes:

	[cornerRadiusAnimation addKeyFrame:[[IFTTTAnimationKeyFrame alloc] initWithTime:0 andCornerRadius:originView.layer.cornerRadius]];
	[cornerRadiusAnimation addKeyFrame:[[IFTTTAnimationKeyFrame alloc] initWithTime:screenWidth andCornerRadius:targetView.layer.cornerRadius]];

Also, logging those values right before the snippet above gives me this:

>2015-03-20 17:14:10.491 AppName[17978:1043969] originView.layer.cornerRadius: 0.000000
2015-03-20 17:14:10.491 AppName[17978:1043969] targetView.layer.cornerRadius: 4.000000

Also, I use a _frame animation_ on the `originView` too; could that be interfering with this one?

**Comment by jhersh** [comment]
@revolter hard to say without seeing more of your code. Generally you'll need to attach that animation to an animator and ensure you're advancing the time as your scrollview's offset changes. It should be fine to have multiple animations on the same view.

**Comment by revolter** [comment]
Well, I have these functions:

	- (void)addColorAnimationFor:(UIView *)originView toView:(UIView *)targetView atPage:(Page)page {

		IFTTTColorAnimation *colorAnimation = [[IFTTTColorAnimation alloc] initWithView:originView];

		[colorAnimation addKeyFrame:[[IFTTTAnimationKeyFrame alloc] initWithTime:page.left andColor:originView.backgroundColor]];
		[colorAnimation addKeyFrame:[[IFTTTAnimationKeyFrame alloc] initWithTime:page.right andColor:targetView.backgroundColor]];

		[animator addAnimation:colorAnimation];
	}

	- (void)addCornerRadiusAnimationFor:(UIView *)originView toView:(UIView *)targetView atPage:(Page)page {

		IFTTTCornerRadiusAnimation *cornerRadiusAnimation = [[IFTTTCornerRadiusAnimation alloc] initWithView:originView];

		[cornerRadiusAnimation addKeyFrame:[[IFTTTAnimationKeyFrame alloc] initWithTime:page.left andCornerRadius:originView.layer.cornerRadius]];
		[cornerRadiusAnimation addKeyFrame:[[IFTTTAnimationKeyFrame alloc] initWithTime:page.right andCornerRadius:targetView.layer.cornerRadius]];

		[animator addAnimation:cornerRadiusAnimation];
	}

and this:

	[self addColorAnimationFor:firstPageLabel toView:secondPageLabel atPage:page];
	[self addCornerRadiusAnimationFor:firstPageLabel toView:secondPageLabel atPage:page];

and the first one works, but the second one doesn't. As you can see, the general idea is the same. Also, I already made sure to do what you said, I have more animations besides these two but the corner radius is the single one that doesn't work _(meaning that it doesn't change the original `cornerRadius` at all)_.

**Comment by revolter** [comment]
@jhersh, I tried on a completely different view and it worked, with a target corner radius of 60 and even 4 like the first example. That means that the problem is somewhere else, so I'll solve it myself. If you want, I can delete my _(now useless)_ comments here.

**Comment by nunogoncalves** [comment]
I'm just gonna say to try and add bigger and hard coded radius to see of you spot any difference. Maybe this is a useless guess I'm making here but who knows. :)

**Comment by revolter** [comment]
I tried with:

	[cornerRadiusAnimation addKeyFrame:[[IFTTTAnimationKeyFrame alloc] initWithTime:page.left andCornerRadius:0]];
	[cornerRadiusAnimation addKeyFrame:[[IFTTTAnimationKeyFrame alloc] initWithTime:page.right andCornerRadius:40]];

But it still doesn't work. So as I said, it's somewhere else. Thanks for your interest though!

**Comment by revolter** [comment]
@jhersh, @nunogoncalves I figured it out. I was trying to animate the `cornerRadius` for an `UILabel`, so it needed it's `layer.masksToBounds` property set to `YES`.

**Pull request merged**
