### PR TITLE
CAShapeLayer: strokeStart, strokeEnd, fillColor properties animation

### PR DESCRIPTION
**Pull request by pNre**
Hi, in this PR I've added an initializer, with a `CALayer`, to `IFTTTAnimation` and 3 `IFTTTAnimation` subclasses to animate:

* `CAShapeLayer.strokeStart`
* `CAShapeLayer.strokeEnd`
* `CAShapeLayer.fillColor`

Here's an example animation for `strokeEnd` (from 1 to 0) and `fillColor` (from blue to clear):

anim1

### CODE REVIEW

**Comment by confile** [comment]
+1 hope this gets merged!

**Comment by steffimueller** [comment]
+1 this is awesome!. Please merge this request.

**Comment by lauraskelton** [comment]
This looks awesome, thanks for contributing! (and sorry for the delay!)

**Comment by confile** [comment]
@coveralls Could you please provide an example if how to use it?

**Pull request merged**
