### PR TITLE
Added text color animation

### PR DESCRIPTION
**Pull request by revolter**
Maybe the `IFTTTColorAnimation` could be renamed to `IFTTTBackgroundColorAnimation` to clear the confusion.

### CODE REVIEW

**Comment by lauraskelton** [comment]
@revolter It looks like you might need to run `pod update 'JazzHands'` from the Example folder of JazzHands to make sure that your new files are included in the project- it's currently not building because of this.

**Comment by revolter** [comment]
Done

**Comment by revolter** [comment]
Ok, I don't understand why it fails and what should I do. I'm not so used with Github.

**Comment by lauraskelton** [comment]
It looks like that fixed the build issue, but now one of our super strict automatic code checkers is complaining that in the header comments of your file IFTTTTextColorAnimation you are calling it IFTTTColorAnimation. If you fix that (in both the .m and .h files) it should be good to go!

**Comment by revolter** [comment]
Wow, awesome. Is this check included in something open source or is it custom made? And, how comes it's not checking for trailing whitespace?

**Comment by lauraskelton** [comment]
That one is a linter that specifically checks the header style and makes sure the class names match. This is looking great, thanks for fixing it!

**Comment by revolter** [comment]
And thanks for merging it!

**Pull request merged**
