### PR TITLE
Swipe Animation

### PR DESCRIPTION
**Pull request by ashavit**
Hi,
I added a new animation class.
The purpose is to create a swipe animation using the views mask.
Please consider pushing to production pod.
Thanx.

### CODE REVIEW

**Comment by lauraskelton** [comment]
Cool! 

There's an issue with the CI build failing for this pull request. It looks like the version of CocoaPods you were using is older- perhaps updating cocoa pods to v38 and running pod install again would help?

**Comment by ashavit** [comment]
@lauraskelton Fixed it.
Turns out that there were some missing files that broke the compilation.
I removed them from from the git ignore list so the compilation runs now.
Thanx.

**Comment by lauraskelton** [comment]
@ashavit I finally had a chance to test this out- it looks awesome! What a great addition to JazzHands.

I'm all ready to merge it in, but could you make a quick fix to the headers of `IFTTTMaskAnimation.h` and `IFTTTMaskAnimation.m` to be consistent with the rest of the project?

Instead of 
```
//  Onborading Experience
```
it should say 
```
//  JazzHands
```

and instead of

```
//  Copyright (c) 2015 Autodesk. All rights reserved.
```

it should say 

```
//  Copyright (c) 2015 IFTTT Inc. All rights reserved.
```

Otherwise, this looks fantastic!

**Comment by ashavit** [comment]
@lauraskelton Done. Thanx :)

**Pull request merged**
